import json

from fastapi import FastAPI, UploadFile, File, Form

from app.engine import process_audio
from app.analysis import analyze_audio

app = FastAPI(title="MixSmvrt DSP Engine")


@app.post("/analyze")
async def analyze(file: UploadFile = File(...)):
    """Return analysis stats and reference-based preset overrides."""
    return analyze_audio(file)


@app.post("/process")
async def process(
    file: UploadFile = File(...),
    track_type: str = Form("vocal"),
    preset: str = Form("clean_vocal"),
    genre: str | None = Form(None),
    reference_profile: str | None = Form(None),
):
    """Process an uploaded audio file with the given track type + preset.

    Optionally accepts a ``reference_profile`` JSON string containing
    ``preset_overrides`` generated by the /analyze endpoint.
    """

    gender: str | None = None
    overrides_dict = None
    if reference_profile:
        try:
            parsed = json.loads(reference_profile)
            # Frontend typically passes the ``preset_overrides`` object.
            overrides_dict = parsed.get("preset_overrides", parsed)
        except Exception:  # pragma: no cover - defensive parsing
            overrides_dict = None

    output_path = process_audio(file, track_type, preset, genre, gender, overrides_dict)
    return {
        "status": "processed",
        "output_file": output_path,
        "track_type": track_type,
        "preset": preset,
        "genre": genre,
        "gender": gender,
    }
