import json
from dataclasses import asdict

from fastapi import FastAPI, UploadFile, File, Form, Query
from fastapi.middleware.cors import CORSMiddleware

from app.engine import process_audio
from app.analysis import analyze_audio
from app.preset_registry import list_presets

app = FastAPI(title="MixSmvrt DSP Engine")

# Allow the Vercel studio and local development to call this DSP service
app.add_middleware(
    CORSMiddleware,
    allow_origins=[
        "https://mixsmvrt.vercel.app",
        "http://localhost:3000",
    ],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)


@app.post("/analyze")
async def analyze(file: UploadFile = File(...)):
    """Return analysis stats and reference-based preset overrides."""
    return analyze_audio(file)


@app.post("/process")
async def process(
    file: UploadFile = File(...),
    track_type: str = Form("vocal"),
    preset: str = Form("clean_vocal"),
    genre: str | None = Form(None),
    reference_profile: str | None = Form(None),
):
    """Process an uploaded audio file with the given track type + preset.

    Optionally accepts a ``reference_profile`` JSON string containing
    ``preset_overrides`` generated by the /analyze endpoint.
    """

    gender: str | None = None
    overrides_dict = None
    if reference_profile:
        try:
            parsed = json.loads(reference_profile)
            # Frontend typically passes the ``preset_overrides`` object.
            overrides_dict = parsed.get("preset_overrides", parsed)
        except Exception:  # pragma: no cover - defensive parsing
            overrides_dict = None

    output_path = process_audio(file, track_type, preset, genre, gender, overrides_dict)
    return {
        "status": "processed",
        "output_file": output_path,
        "track_type": track_type,
        "preset": preset,
        "genre": genre,
        "gender": gender,
    }


@app.get("/presets")
async def list_available_presets(kind: str | None = Query(default=None)):
    """Return the catalog of presets known to the DSP engine.

    Optional query parameter ``kind`` can be one of ``vocal``, ``mix`` or
    ``master`` to filter the list. The response is structured for direct
    consumption by the studio or admin UI.
    """

    normalized: str | None
    if kind in {"vocal", "mix", "master"}:
        normalized = kind
    else:
        normalized = None

    presets = list_presets(kind=normalized)  # type: ignore[arg-type]
    return {
        "presets": [asdict(p) for p in presets],
    }
